# Generated by Django 4.2.2 on 2023-06-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_membership_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmembership',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='privatesession',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Rescheduled'), (3, 'Cancelled'), (4, 'Pending')], default=4),
        ),
    ]
