# Generated by Django 4.2.2 on 2023-06-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_client_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tier_access',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contentactivity',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='backend.client'),
        ),
    ]
