# Generated by Django 4.2.2 on 2023-06-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
